module Horologium
  module Scales
    class Base
      def self.from_reference: (Numeric::TwoPartFloat | Numeric::Exact value, Symbol precision) -> (Numeric::TwoPartFloat | Numeric::Exact)

      def self.to_reference: (Numeric::TwoPartFloat | Numeric::Exact value, Symbol precision) -> (Numeric::TwoPartFloat | Numeric::Exact)

      def self.seconds_in_day: (Integer day_number) -> Integer

      def self.si_seconds_in_day: (Integer day_number) -> (Integer | Rational)

      def self.zone_designator: () -> String

      def self.provenance: (Numeric::TwoPartFloat | Numeric::Exact value) -> Symbol
    end
  end
end
