module Horologium
  module Numeric
    class Exact
      def initialize: (Integer | Float | Rational | TwoPartFloat | Exact value) -> void

      def ==: (untyped other) -> bool

      def eql?: (untyped other) -> bool

      def hash: () -> Integer

      def to_r: () -> Rational

      attr_reader value: Rational
    end
  end
end
