module Horologium
  module Numeric
    class Exact
      def initialize: (scalar | TwoPartFloat | Exact value) -> void

      def +: (Exact other) -> Exact

      def -: (Exact other) -> Exact

      def *: (scalar scalar) -> Exact

      def /: (scalar scalar) -> Exact

      def ==: (untyped other) -> bool

      def eql?: (untyped other) -> bool

      def hash: () -> Integer

      def to_r: () -> Rational

      attr_reader value: Rational
    end
  end
end
