module Horologium
  module Numeric
    class Exact
      def initialize: (scalar | TwoPartFloat | Exact value) -> void

      def +: (Exact other) -> Exact

      def -: (Exact other) -> Exact

      def *: (scalar scalar) -> Exact

      def /: (scalar scalar) -> Exact

      def ==: (untyped other) -> bool

      def eql?: (untyped other) -> bool

      def hash: () -> Integer

      def to_r: () -> Rational

      def zero?: () -> bool

      def negative?: () -> bool

      def positive?: () -> bool

      def to_f: () -> Float

      attr_reader value: Rational

      private

      def scalar_rational: (untyped scalar) -> Rational
    end
  end
end
