module Horologium
  module Numeric
    module Precision
      NAMES: Array[Symbol]

      def self.validate!: (Symbol precision) -> Symbol

      def self.resolve: (Symbol left, Symbol right) -> Symbol

      def self.coerce: (TwoPartFloat | Exact value, to: :exact) -> Exact
                     | (TwoPartFloat | Exact value, to: :standard) -> TwoPartFloat
                     | (TwoPartFloat | Exact value, to: Symbol) -> (TwoPartFloat | Exact)

      def self.number!: (untyped value) -> scalar

      def self.finite_float!: (untyped value) -> Float

      private def self.value!: (untyped value) -> (TwoPartFloat | Exact)

      def self.build_each: (scalar value) -> Hash[Symbol, TwoPartFloat | Exact]

      def self.build: (scalar value, Symbol precision) -> (TwoPartFloat | Exact)

      def self.add: (TwoPartFloat | Exact left, TwoPartFloat | Exact right) -> (TwoPartFloat | Exact)

      def self.subtract: (TwoPartFloat | Exact left, TwoPartFloat | Exact right) -> (TwoPartFloat | Exact)

      def self.compare: (TwoPartFloat | Exact left, TwoPartFloat | Exact right) -> Integer

      def self.validate_value!: (TwoPartFloat | Exact value, Symbol precision) -> (TwoPartFloat | Exact)

      def self.value_type: (Symbol precision) -> Class

      private def self.sign_of: (Float | Rational number) -> Integer

      private def self.promote: (TwoPartFloat | Exact value) -> Exact
    end
  end
end
