module Horologium
  module Numeric
    class TwoPartFloat
      def initialize: (Float high, ?Float low) -> void

      def +: (TwoPartFloat other) -> TwoPartFloat

      def -: (TwoPartFloat other) -> TwoPartFloat

      def ==: (untyped other) -> bool

      def eql?: (untyped other) -> bool

      def hash: () -> Integer

      def self.normalize: (Float high, ?Float low) -> TwoPartFloat

      def self.two_sum: (Float left, Float right) -> [ Float, Float ]

      def self.two_diff: (Float left, Float right) -> [ Float, Float ]

      def self.fast_two_sum: (Float larger, Float smaller) -> [ Float, Float ]

      attr_reader high: Float

      attr_reader low: Float

      private

      def two_sum: (Float left, Float right) -> [ Float, Float ]

      def two_diff: (Float left, Float right) -> [ Float, Float ]

      def fast_two_sum: (Float larger, Float smaller) -> [ Float, Float ]
    end
  end
end
