module Horologium
  module Numeric
    class TwoPartFloat
      SPLIT_FACTOR: Float

      def initialize: (Float high, ?Float low) -> void

      def +: (TwoPartFloat other) -> TwoPartFloat

      def -: (TwoPartFloat other) -> TwoPartFloat

      def *: (scalar scalar) -> TwoPartFloat

      def /: (scalar scalar) -> TwoPartFloat

      def to_r: () -> Rational

      def zero?: () -> bool

      def negative?: () -> bool

      def positive?: () -> bool

      def to_f: () -> Float

      def ==: (untyped other) -> bool

      def eql?: (untyped other) -> bool

      def hash: () -> Integer

      def self.normalize: (Float high, ?Float low) -> TwoPartFloat

      def self.from_real: (scalar value) -> TwoPartFloat

      def self.two_sum: (Float left, Float right) -> [ Float, Float ]

      def self.sum_error: (Float left, Float right, Float sum) -> Float

      def self.two_diff: (Float left, Float right) -> [ Float, Float ]

      def self.difference_error: (Float left, Float right, Float difference) -> Float

      def self.fast_two_sum: (Float larger, Float smaller) -> [ Float, Float ]

      def self.fast_sum_error: (Float larger, Float smaller, Float sum) -> Float

      def self.two_product: (Float left, Float right) -> [ Float, Float ]

      def self.product_error: (Float left, Float right, Float product) -> Float

      def self.split: (Float value) -> [ Float, Float ]

      def self.split_high: (Float value) -> Float

      attr_reader high: Float

      attr_reader low: Float

      private

      def scalar_float: (untyped scalar) -> Float

    end
  end
end
