module Horologium
  class Configuration
    BUILT_IN_SCALES: Hash[Symbol, singleton(Scales::Base)]

    LEAP_SECOND_HORIZONS: Array[Symbol]

    @default_precision: Symbol

    @scales: Hash[Symbol, singleton(Scales::Base)]

    @leap_second_source: untyped

    @leap_second_horizon: Symbol

    attr_reader default_precision: Symbol

    attr_reader eop_source: untyped

    attr_reader leap_second_source: untyped

    attr_reader leap_second_horizon: Symbol

    def initialize: () -> void

    def scale_names: () -> Array[Symbol]

    def default_precision=: (Symbol precision) -> Symbol

    def eop_source=: (untyped source) -> untyped

    def leap_second_source=: (untyped source) -> untyped

    def leap_second_horizon=: (Symbol horizon) -> Symbol

    def register_scale: (Symbol name, singleton(Scales::Base) scale) -> singleton(Scales::Base)

    def scale: (Symbol name) -> singleton(Scales::Base)

    def freeze: () -> self

    private

    def validate_scale!: (untyped scale) -> void
  end
end
