module Horologium
  class Instant
    include PreciseValue

    type julian_date = String | Rational | Integer | Float

    type julian_date_part = Float | Integer

    def self.from_julian_date: (julian_date value, ?julian_date_part? low, scale: Symbol, ?precision: Symbol) -> Instant

    def self.from_modified_julian_date: (julian_date value, ?julian_date_part? low, scale: Symbol, ?precision: Symbol) -> Instant

    private def self.from_representation: (untyped representation, julian_date value, julian_date_part? low, Symbol scale, Symbol precision) -> Instant

    def +: (Duration duration) -> Instant

    def -: (Duration) -> Instant
         | (Instant) -> Duration

    def to: (Symbol scale) -> ScaleReading

    def as: (Symbol representation, scale: Symbol, ?as: Symbol) -> untyped

    def equal_within?: (Instant other, Duration tolerance) -> bool

    private

    def seconds_to_days: (Duration duration, Symbol precision) -> (Numeric::TwoPartFloat | Numeric::Exact)
  end
end
