module Horologium
  class Instant
    include PreciseValue

    type julian_date = String | Rational | Integer | Float

    type julian_date_part = Float | Integer

    def self.from_julian_date: (julian_date value, ?julian_date_part? low, scale: Symbol, ?precision: Symbol) -> Instant

    def self.from_modified_julian_date: (julian_date value, ?julian_date_part? low, scale: Symbol, ?precision: Symbol) -> Instant

    def self.from_civil: (Representations::CivilTime civil, scale: Symbol, ?precision: Symbol) -> Instant
                       | (Integer year, Integer month, Integer day, ?Integer hour, ?Integer minute, ?Representations::Civil::second second, scale: Symbol, ?precision: Symbol) -> Instant

    def self.from_tai: (Representations::CivilTime civil, ?precision: Symbol) -> Instant
                     | (Integer year, Integer month, Integer day, ?Integer hour, ?Integer minute, ?Representations::Civil::second second, ?precision: Symbol) -> Instant

    def self.from_tt: (Representations::CivilTime civil, ?precision: Symbol) -> Instant
                    | (Integer year, Integer month, Integer day, ?Integer hour, ?Integer minute, ?Representations::Civil::second second, ?precision: Symbol) -> Instant

    def self.from_tdb: (Representations::CivilTime civil, ?precision: Symbol) -> Instant
                     | (Integer year, Integer month, Integer day, ?Integer hour, ?Integer minute, ?Representations::Civil::second second, ?precision: Symbol) -> Instant

    def self.from_tcg: (Representations::CivilTime civil, ?precision: Symbol) -> Instant
                       | (Integer year, Integer month, Integer day, ?Integer hour, ?Integer minute, ?Representations::Civil::second second, ?precision: Symbol) -> Instant

    def self.from_tcb: (Representations::CivilTime civil, ?precision: Symbol) -> Instant
                       | (Integer year, Integer month, Integer day, ?Integer hour, ?Integer minute, ?Representations::Civil::second second, ?precision: Symbol) -> Instant

    def self.from_gps: (Representations::CivilTime civil, ?precision: Symbol) -> Instant
                       | (Integer year, Integer month, Integer day, ?Integer hour, ?Integer minute, ?Representations::Civil::second second, ?precision: Symbol) -> Instant

    def self.from_utc: (Representations::CivilTime civil, ?precision: Symbol) -> Instant
                     | (Integer year, Integer month, Integer day, ?Integer hour, ?Integer minute, ?Representations::Civil::second second, ?precision: Symbol) -> Instant

    def self.from_ut1: (Representations::CivilTime civil, ?precision: Symbol) -> Instant
                     | (Integer year, Integer month, Integer day, ?Integer hour, ?Integer minute, ?Representations::Civil::second second, ?precision: Symbol) -> Instant

    def self.from_time: (Time time, ?precision: Symbol) -> Instant

    def self.now: (?precision: Symbol) -> Instant

    def self.from_unix: (Numeric::scalar seconds, ?precision: Symbol) -> Instant

    def self.from_offset: (Instant origin, Duration elapsed) -> Instant

    def self.from_iso8601: (String value, scale: Symbol, ?precision: Symbol) -> Instant

    private def self.civil_time: (untyped year, untyped month, untyped day, untyped hour, untyped minute, untyped second) -> Representations::CivilTime

    private def self.from_representation: (untyped representation, untyped value, julian_date_part? low, Symbol scale, Symbol precision) -> Instant

    def +: (Duration duration) -> Instant

    def -: (Duration) -> Instant
         | (Instant) -> Duration

    def to: (Symbol scale) -> ScaleReading

    def as: (Symbol representation, scale: Symbol, ?as: Symbol) -> untyped

    def equal_within?: (Instant other, Duration tolerance) -> bool

    def inspect: () -> String

    private

    def seconds_to_days: (Duration duration, Symbol precision) -> (Numeric::TwoPartFloat | Numeric::Exact)
  end
end
