module Horologium
  module PreciseValue
    include Comparable

    @value: Numeric::TwoPartFloat | Numeric::Exact

    @precision: Symbol

    def initialize: (Numeric::TwoPartFloat | Numeric::Exact value, Symbol precision) -> void

    attr_reader value: Numeric::TwoPartFloat | Numeric::Exact

    attr_reader precision: Symbol

    def rational: () -> Rational

    def <=>: (untyped other) -> Integer?

    def eql?: (untyped other) -> bool

    def hash: () -> Integer
  end
end
