module Horologium
  class ScaleReading
    REPRESENTATIONS: Hash[Symbol, singleton(Representations::JulianDate) | singleton(Representations::ModifiedJulianDate) | singleton(Representations::Civil) | singleton(Representations::Iso8601)]

    @scale: Symbol

    @value: Numeric::TwoPartFloat | Numeric::Exact

    @precision: Symbol

    @provenance: Symbol

    attr_reader scale: Symbol

    attr_reader precision: Symbol

    attr_reader value: Numeric::TwoPartFloat | Numeric::Exact

    attr_reader provenance: Symbol

    def initialize: (Symbol scale, Numeric::TwoPartFloat | Numeric::Exact value, Symbol precision, ?Symbol provenance) -> void

    def as: (Symbol representation, ?as: Symbol) -> untyped
  end
end
